---
title: "Exploring the Synergistic Influences of Labor, Environmental, and Plantation Management Practices in the Rubber Latex Production Industry"
---

This website serves as the home for the supplementary documents for the paper **"Exploring the Synergistic Influences of Labor, Environmental, and Plantation Management Practices in the Rubber Latex Production Industry"** by **B. S. S. Cooraya, T. S. Talagala, R. P. Hettiarachchige, Upul Subasinghe.** It provides access to additional materials, datasets, code, figures, and supporting information related to the study.

The goal of this website is to promote reproducible research and open access by making the research process transparent, accessible, and easy to verify. By sharing these resources, we aim to support collaboration, facilitate further research, and encourage the reuse of methods and findings by the wider research community.

**Our team**

B. S. S. Cooraya

Dr. T. S. Talagala

R. P. Hettiarachchige

Snr. Prof.Upul Subasinghe: Corresponding author and team leader

